# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_dgdt0 <- function(times, Fs,  Ys, g0, Lambda0, h0, h1, A, Ne, treeT) {
    .Call('skyspline_solve_dgdt0', PACKAGE = 'skyspline', times, Fs,  Ys, g0, Lambda0, h0, h1, A, Ne, treeT)
}

solve_CoM12L <- function(times, Fs,  Ys,  Lambda0, h0, h1, A) {
    .Call('skyspline_solve_CoM12L', PACKAGE = 'skyspline', times, Fs,  Ys,  Lambda0, h0, h1, A)
}

update_lambda_gx_node <- function(A, Ne, g_x, y) {
    .Call('skyspline_update_lambda_gx_node', PACKAGE = 'skyspline', A, Ne, g_x, y)
}

update_lambda_gx_node2 <- function(A, Ne, g_x, y) {
    .Call('skyspline_update_lambda_gx_node2', PACKAGE = 'skyspline', A, Ne, g_x, y)
}

solve_semiPar0 <- function(t0, t1, res, y0, betas, gamma, eps_abs = 1.0e-10, eps_rel = 1.0e-6) {
    .Call('skyspline_solve_semiPar0', PACKAGE = 'skyspline', t0, t1, res, y0, betas, gamma, eps_abs, eps_rel)
}

eventTimes2extant <- function(eventTimes, nodeheights, parentheights) {
	.Call( 'sourceCpp_0_eventTimes2extant' , PACKAGE='skyspline'
	, eventTimes, nodeheights, parentheights)
}
